name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GFJPROXY_REDIS_URL: "redis://localhost:6379/"
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        version: "0.9.13"
    - uses: supercharge/redis-github-action@v2
      with:
        redis-version: 7
    - run: |
        uv sync --locked --all-extras --dev
    - run: |
        uv run ruff check
    - run: |
        uv run pytest
